"""
Django settings for jobportal project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Add these settings to your settings.py for deployment

import os
import environ
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# OpenAI API settings
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# CSRF Settings
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False  # False to allow JavaScript access
CSRF_COOKIE_SAMESITE = 'Lax'

# Session Settings
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'

# Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_SSL_REDIRECT = False

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Comment out the PostgreSQL configuration for now
# if os.getenv('DATABASE_URL'):
#     import dj_database_url
#     DATABASES = {
#         'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'jobportal',  # Replace with your database name
#             'USER': 'jobportal',      # Replace with your username
#             'PASSWORD': 'rianne13!',  # Replace with your password
#             'HOST': 'localhost',
#             'PORT': '5432',
#         }
#     }

ROOT_URLCONF = 'jobportal.urls'  # Replace 'jobportal' with your project's name

# Add these to your Django settings.py

        # Add TEMPLATES here
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # General project templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_processor',
                'users.context_processors.conversation_processor',
            ],
        },
    },
]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third-party apps
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    
    # Local apps
    'jobs',
    'users',
    'ai_matching',
]

# Django Channels
INSTALLED_APPS += [
    'channels',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Authentication settings
AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Site settings
SITE_ID = 1
SITE_DOMAIN = 'localhost:8000'
SITE_NAME = 'Worksy'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'jobportal', 'static'),  # Make sure this directory exists
]

# AllAuth settings
# Modern django-allauth settings (replacing deprecated ones)

ACCOUNT_LOGIN_METHODS = ['username', 'email']  # Allow login with username or email
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'email2*', 'password', 'password2'] # Required fields for signup

# Rate limiting for login attempts
ACCOUNT_RATE_LIMITS = {'login_failed': '5/300'}  # 5 failed login attempts in 300 seconds

# Remaining settings (no direct replacements, but still relevant)

ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Mandatory email verification
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Confirm email on GET request
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Email confirmation link expires in 3 days
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'Worksy - '  # Subject prefix for email messages
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'  # Default HTTP protocol
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Log in automatically after email confirmation
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True  # Log out after password change
ACCOUNT_USERNAME_MIN_LENGTH = 4  # Minimum username length

# No longer needed, as they are now handled by ACCOUNT_SIGNUP_FIELDS and ACCOUNT_RATE_LIMITS
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# Custom adapters
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'

# Social account providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'github': {
         'APP': {
            'client_id': 'Ov23li8pw8gPYLewaFyj',
            'secret': 'c6fc43d7a8d4bab0b369e25dee6440446044c165',
        },
        'SCOPE': [
            'user',
            'user:email',
        ],
    }
}

# Login settings
LOGIN_URL = 'users:applicant_login'
LOGIN_REDIRECT_URL = 'users:applicant_dashboard'
LOGOUT_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # Your Gmail address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Your app password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# For Docker PostgreSQL
DB_NAME = env("DB_NAME")
DB_USER = env("DB_USER")
DB_PASSWORD = env("DB_PASSWORD")

ASGI_APPLICATION = 'jobportal.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379/0')],
        },
    },
}

# Social Auth settings
SOCIAL_AUTH_GITHUB_KEY = os.environ.get('GITHUB_CLIENT_ID')
SOCIAL_AUTH_GITHUB_SECRET = os.environ.get('GITHUB_CLIENT_SECRET')

# Social Auth Configuration
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/users/applicant/dashboard/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/users/applicant/login/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/users/applicant/dashboard/'
SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = '/users/applicant/dashboard/'

# GitHub specific settings
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']